name: OceanWorldGenerator
main: com.liamxsage.oceanworldgenerator.OceanWorldGenerator
version: ${version}
description: "Generates a world with a warm ocean"
author: "LiamXSage"
api-version: "1.21"
loader: com.liamxsage.oceanworldgenerator.DependencyLoader
load: STARTUP